artifact_location: file:///Volumes/PRO-BLADE/Github/orpheus-engine/demo/orpheus_mlflow_demo/684094645672163162
creation_time: 1749546453958
experiment_id: '684094645672163162'
last_update_time: 1749546453958
lifecycle_stage: active
name: orpheus-audio-analysis-hp-ai-studio
