artifact_uri: file:///Volumes/PRO-BLADE/Github/orpheus-engine/demo/orpheus_mlflow_demo/887071984579510525/32ff0b870a9f4ac2897df52bc41e37db/artifacts
end_time: 1749550544679
entry_point_name: ''
experiment_id: '887071984579510525'
lifecycle_stage: active
run_id: 32ff0b870a9f4ac2897df52bc41e37db
run_name: audio_analysis_3
run_uuid: 32ff0b870a9f4ac2897df52bc41e37db
source_name: ''
source_type: 4
source_version: ''
start_time: 1749550544550
status: 3
tags: []
user_id: jeldonmusic
