artifact_uri: file:///Volumes/PRO-BLADE/Github/orpheus-engine/demo/orpheus_mlflow_demo/887071984579510525/42be6dd0ea934ee09354dd23efc2252c/artifacts
end_time: 1749550545543
entry_point_name: ''
experiment_id: '887071984579510525'
lifecycle_stage: active
run_id: 42be6dd0ea934ee09354dd23efc2252c
run_name: model_registration_demo
run_uuid: 42be6dd0ea934ee09354dd23efc2252c
source_name: ''
source_type: 4
source_version: ''
start_time: 1749550545472
status: 3
tags: []
user_id: jeldonmusic
