artifact_uri: file:///Volumes/PRO-BLADE/Github/orpheus-engine/demo/orpheus_mlflow_demo/887071984579510525/ca6c4dc788034fe4bc046f937b917edf/artifacts
end_time: 1749550545601
entry_point_name: ''
experiment_id: '887071984579510525'
lifecycle_stage: active
run_id: ca6c4dc788034fe4bc046f937b917edf
run_name: hp_ai_studio_final_report
run_uuid: ca6c4dc788034fe4bc046f937b917edf
source_name: ''
source_type: 4
source_version: ''
start_time: 1749550545558
status: 3
tags: []
user_id: jeldonmusic
