artifact_uri: file:///Volumes/PRO-BLADE/Github/orpheus-engine/demo/orpheus_mlflow_demo/887071984579510525/f72cd1d4315c40a3bda7adee7a5ce05d/artifacts
end_time: 1750284636050
entry_point_name: ''
experiment_id: '887071984579510525'
lifecycle_stage: active
run_id: f72cd1d4315c40a3bda7adee7a5ce05d
run_name: audio_analysis_3
run_uuid: f72cd1d4315c40a3bda7adee7a5ce05d
source_name: ''
source_type: 4
source_version: ''
start_time: 1750284635991
status: 3
tags: []
user_id: jeldonmusic
