artifact_uri: file:///Volumes/PRO-BLADE/Github/orpheus-engine/demo/orpheus_mlflow_demo/887071984579510525/2aa2ae8bcdcc4c16afd0566d73d5a0a5/artifacts
end_time: 1749550544546
entry_point_name: ''
experiment_id: '887071984579510525'
lifecycle_stage: active
run_id: 2aa2ae8bcdcc4c16afd0566d73d5a0a5
run_name: audio_analysis_2
run_uuid: 2aa2ae8bcdcc4c16afd0566d73d5a0a5
source_name: ''
source_type: 4
source_version: ''
start_time: 1749550544452
status: 3
tags: []
user_id: jeldonmusic
