artifact_location: file:///Volumes/PRO-BLADE/Github/orpheus-engine/demo/orpheus_mlflow_demo/887071984579510525
creation_time: 1749550544294
experiment_id: '887071984579510525'
last_update_time: 1749550544294
lifecycle_stage: active
name: orpheus-audio-analysis-hp-ai-studio
