name: Pre-release Workflow

on:
  push:
    branches: 
      - 'release/v*-alpha'
      - 'release/v*-beta'
  workflow_dispatch:
    inputs:
      version:
        description: 'Pre-release version (e.g., 2.0.0-alpha.1)'
        required: true
      type:
        description: 'Pre-release type (alpha/beta)'
        required: true
        default: 'alpha'

jobs:
  pre-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Fix permissions and Install dependencies
        run: |
          npm run fix-permissions
          npm run install-all
        
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
      - name: Update version
        if: github.event_name == 'workflow_dispatch'
        run: |
          npm version ${{ github.event.inputs.version }} --no-git-tag-version
          git add package.json
          git commit -m "chore(release): v${{ github.event.inputs.version }}"
          
      - name: Create pre-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(node -p "require('./package.json').version")
          gh release create v$VERSION \
            --prerelease \
            --title "Pre-release v$VERSION" \
            --notes "This is a pre-release version of Orpheus Engine. Please note that this version may contain experimental features and is not recommended for production use."
