name: Release Workflow
permissions:
  contents: write
on:
  push:
    branches: [main]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '!v*-*'  # Exclude pre-release tags
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 2.0.0)'
        required: true
      type:
        description: 'Release type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
        
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Fix permissions and Install dependencies
        run: |
          npm run fix-permissions
          npm run install-all
        
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
      - name: Create Release
        if: github.event_name == 'workflow_dispatch'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout main
          git pull origin main
          # Map the input type to the correct npm script
          if [ "${{ github.event.inputs.type }}" = "patch" ]; then
            npm run release:patch
          elif [ "${{ github.event.inputs.type }}" = "minor" ]; then
            npm run release:minor
          elif [ "${{ github.event.inputs.type }}" = "major" ]; then
            npm run release:major
          else
            npm run release:patch
          fi
          
      - name: Push Tags
        run: |
          git push origin --tags
