name: Sync Package Versions

on:
  # Run when a new release is published
  release:
    types: [published]
  
  # Manually trigger this workflow
  workflow_dispatch:

jobs:
  sync-versions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Git identity
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      
      - name: Fix permissions and Install dependencies
        run: |
          npm run fix-permissions
          npm run install-all
      
      - name: Run version sync script
        run: npm run sync-versions
      
      - name: Commit and push version changes
        run: |
          git add -A
          git diff-index --quiet HEAD || git commit -m "chore: sync package versions [automated]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
