name: Sync Version

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  sync-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Get latest release version
        id: get_version
        run: |
          LATEST_VERSION=$(git describe --tags --abbrev=0)
          echo "latest_version=${LATEST_VERSION}" >> $GITHUB_OUTPUT
          
      - name: Sync versions across packages
        run: npm run sync-versions
        
      - name: Update local packages
        run: |
          VERSION=${{ steps.get_version.outputs.latest_version }}
          VERSION=${VERSION#v}
          echo "Syncing to version $VERSION"
          npm version $VERSION --no-git-tag-version --workspaces
          
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "chore: sync version to ${{ steps.get_version.outputs.latest_version }}" || echo "No changes to commit"
          git push
